version: "3.8"

services:
  db:
    image: postgres:13.0-alpine
    volumes:
      - data_volume_foodgram:/var/lib/postgresql/data/
    env_file:
      - ./backend/foodgram/foodgram/.env

  web:
    image: foodgram:latest
    restart: always
    volumes:
      - static_volume_foodgram:/app/app/static/
      - media_volume_foodgram:/app/app/media/
    depends_on:
      - db
    env_file:
      - ./backend/foodgram/foodgram/.env

  nginx:
    image: nginx:1.21.3-alpine
    ports:
      - "80:80"
    volumes:
      - ./nginx/nginx_foodgram.conf:/etc/nginx/conf.d/default.conf
      - static_volume_foodgram:/var/html/static/
      - media_volume_foodgram:/var/html/media/
      - ./docs/:/usr/share/nginx/html/api/docs/

    depends_on:
      - web

volumes:
  data_volume_foodgram:
  static_volume_foodgram:
  media_volume_foodgram: