version: "3.8"

services:
  db:
    image: postgres:13.0-alpine
    volumes:
      - data_volume_foodgram:/var/lib/postgresql/data/
    env_file:
      - ./backend/foodgram/foodgram/.env

  web:
    image: foodgram:latest
    restart: always
    ports:
      - "8000:8000"
    volumes:
      - static_volume_foodgram:/app/static/
      - media_volume_foodgram:/app/media/
    depends_on:
      - db
    env_file:
      - ./backend/foodgram/foodgram/.env

volumes:
  data_volume_foodgram:
  static_volume_foodgram:
  media_volume_foodgram: