# Generated by Django 4.1.7 on 2023-02-18 18:36

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Tag',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text="Tag's name", max_length=20, unique=True, verbose_name='name')),
                ('color', models.CharField(help_text="Tag's color", max_length=7, unique=True, verbose_name='color')),
                ('slug', models.SlugField(help_text="Tag's slug", max_length=20, unique=True, verbose_name='slug')),
            ],
            options={
                'verbose_name': 'Tag',
                'verbose_name_plural': 'Tags',
                'ordering': ('pk',),
            },
        ),
    ]
