# Generated by Django 4.1.7 on 2023-02-21 13:34

from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('recipes', '0003_alter_ingredient_name_alter_measurementunit_name_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Recipe',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text="Recipe's name", max_length=200, verbose_name='name')),
                ('image', models.FileField(help_text='Recipe image', upload_to='recipe_images', verbose_name='image')),
                ('text', models.TextField(help_text='Recipe description', verbose_name='text')),
                ('cooking_time', models.PositiveSmallIntegerField(help_text='Time of recipe cooking', validators=[django.core.validators.MinValueValidator(1)], verbose_name='cooking_time')),
                ('author', models.ForeignKey(help_text='Author of the recipe', on_delete=django.db.models.deletion.CASCADE, related_name='recipes', to=settings.AUTH_USER_MODEL, verbose_name='author')),
            ],
            options={
                'verbose_name': 'Recipe',
                'verbose_name_plural': 'Recipes',
                'ordering': ('pk',),
            },
        ),
        migrations.CreateModel(
            name='RecipeIngredient',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.PositiveSmallIntegerField(help_text='Ingredient amount used', validators=[django.core.validators.MinValueValidator(1)], verbose_name='amount')),
                ('ingredient', models.ForeignKey(help_text='Ingredient, used in recipe', on_delete=django.db.models.deletion.CASCADE, related_name='recipes', to='recipes.ingredient', verbose_name='ingredient')),
                ('recipe', models.ForeignKey(help_text='Recipe, using this ingredient', on_delete=django.db.models.deletion.CASCADE, related_name='recipe_ingredients', to='recipes.recipe', verbose_name='recipe')),
            ],
            options={
                'verbose_name': 'RecipeIngredient',
                'verbose_name_plural': 'RecipeIngredients',
                'ordering': ('pk',),
            },
        ),
        migrations.AddField(
            model_name='recipe',
            name='ingredients',
            field=models.ManyToManyField(help_text='Ingredients used', related_name='ingredient_recipes', through='recipes.RecipeIngredient', to='recipes.ingredient', verbose_name='ingredients'),
        ),
        migrations.AddField(
            model_name='recipe',
            name='tags',
            field=models.ManyToManyField(help_text="Recipe's tags", to='recipes.tag', verbose_name='tags'),
        ),
    ]
