# Generated by Django 4.1.7 on 2023-02-18 18:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='user',
            options={'ordering': ('pk',), 'verbose_name': 'user', 'verbose_name_plural': 'users'},
        ),
    ]
