name: Foodgram workflow

on: [push]

jobs:
  tests:
    name: Run tests
    runs-on: ubuntu-latest

    services:

      postgres:
        image: postgres
        env:
          POSTGRES_PASSWORD: super-secret-password
        options: >-
          --health-cmd pg_isready
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5
        ports:
          - 5432:5432

    steps:
      - name: Check out the repo
        uses: actions/checkout@v3
      
      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: 3.11

      - name: Install dependencies
        run: |
          python -m pip install -U pip
          python -m pip install flake8 flake8-broken-line flake8-isort flake8-plugin-utils flake8-return
          python -m pip install -r requirements.txt

      - name: Run unittests and tests with flake8
        run: |
          python -m flake8
          cd ./backend/foodgram
          python manage.py test -v 2

  build_and_push_to_docker_hub:
    name: Push Docker image to Docker Hub
    runs-on: ubuntu-latest
    needs: tests
    steps:
      - name: Check out the repo
        uses: actions/checkout@v3
      
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1

      - name: Login to Docker
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}
        
      - name: Push to Docker Hub
        uses: docker/build-push-action@v2
        with:
          push: true
          tags: alexanderup/foodgram:latest
