name: Foodgram workflow

on: [push]

jobs:
  tests:
    name: Run tests
    runs-on: ubuntu-latest

    services:

      postgres:
        image: postgres
        env:
          POSTGRES_PASSWORD: super-secret-password
        options: >-
          --health-cmd pg_isready
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5

    steps:
      - name: Check out the repo
        uses: actions/checkout@v3
      
      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: 3.11

      - name: Install dependencies
        run: |
          python -m pip install -U pip
          python -m pip install flake8 flake8-broken-line flake8-isort flake8-plugin-utils flake8-return
          python -m pip install -r requirements.txt

      - name: Connect to PostgreSQL

      - name: Run tests with flake8
        run: |
          python -m flake8
          cd ./backend/foodgram
          python manage.py test -v 2
